"""Compare MLflow runs programmatically and identify the best one.

Usage:
    python -m src.compare_runs --config configs/config.yaml
    python -m src.compare_runs --export reports   # also write CSV + Markdown
"""

from __future__ import annotations

import argparse
from pathlib import Path

import mlflow
import yaml

DISPLAY_COLUMNS = [
    "tags.mlflow.runName",
    "params.model_type",
    "metrics.accuracy",
    "metrics.precision",
    "metrics.recall",
    "metrics.f1",
    "metrics.roc_auc",
]


def to_markdown_table(df) -> str:
    """Render a small dataframe as a GitHub Markdown table (no extra deps)."""
    cells = df.map(lambda v: f"{v:.4f}" if isinstance(v, float) else str(v))
    header = "| " + " | ".join(cells.columns) + " |"
    divider = "|" + "|".join("---" for _ in cells.columns) + "|"
    rows = ["| " + " | ".join(row) + " |" for row in cells.to_numpy()]
    return "\n".join([header, divider, *rows])


def export_runs(runs, table, metric: str, out_dir: str) -> None:
    """Write the full run history to CSV and a Markdown table.

    These files are committed to the repository (alongside the mlflow.db
    tracking store) as visible evidence of the logged experiment runs.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    keep = [
        c
        for c in runs.columns
        if c in ("run_id", "start_time", "tags.mlflow.runName")
        or c.startswith(("params.", "metrics."))
    ]
    runs[keep].to_csv(out / "experiments.csv", index=False)

    best = runs.iloc[0]
    lines = [
        "# MLflow experiment runs",
        "",
        "Generated by `python -m src.compare_runs --export reports` using",
        f"`mlflow.search_runs()`, ranked by **{metric}**. Every run's full",
        "parameter and metric log is in [experiments.csv](experiments.csv);",
        "the tracking store itself is committed as `mlflow.db` — browse it",
        "with `mlflow ui --backend-store-uri sqlite:///mlflow.db`.",
        "",
        to_markdown_table(table),
        "",
        f"**Best run:** `{best['tags.mlflow.runName']}` "
        f"(run_id `{best['run_id']}`) with {metric}="
        f"{best[f'metrics.{metric}']:.4f}",
        "",
    ]
    (out / "experiments.md").write_text("\n".join(lines), encoding="utf-8")
    print(
        f"\nExported {len(runs)} runs to {out / 'experiments.csv'} "
        f"and {out / 'experiments.md'}"
    )


def compare(config_path: str, metric: str = "roc_auc", export: str | None = None) -> None:
    with open(config_path, encoding="utf-8") as fh:
        config = yaml.safe_load(fh)

    mlflow.set_tracking_uri(config["mlflow"]["tracking_uri"])
    runs = mlflow.search_runs(
        experiment_names=[config["mlflow"]["experiment_name"]],
        order_by=[f"metrics.{metric} DESC"],
    )
    if runs.empty:
        print("No runs logged yet — run `python -m src.train` first.")
        return

    cols = [c for c in DISPLAY_COLUMNS if c in runs.columns]
    table = runs[cols].rename(columns=lambda c: c.split(".", 1)[1])
    print(f"All runs, ranked by {metric}:\n")
    print(table.to_string(index=False))

    best = runs.iloc[0]
    print(
        f"\nBest run: {best['tags.mlflow.runName']} "
        f"(run_id={best['run_id']}) with {metric}="
        f"{best[f'metrics.{metric}']:.4f}"
    )

    if export:
        export_runs(runs, table, metric, export)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/config.yaml")
    parser.add_argument("--metric", default="roc_auc")
    parser.add_argument(
        "--export",
        default=None,
        metavar="DIR",
        help="Also write experiments.csv and experiments.md to DIR",
    )
    args = parser.parse_args()
    compare(args.config, args.metric, args.export)


if __name__ == "__main__":
    main()
